import 'dotenv/config';
import { getPool, closePool } from '../src/db/connection';
import { logger } from '../src/utils/logger';

/**
 * Remove the 13 route/carrier tuples that were generated by
 * scripts/generateSampleT100.ts and then silently overwrote real BTS rows
 * during ingestion (both the fixture and real BTS share source='dot_t100').
 *
 * Run this once after a fresh full-refresh ingest from real BTS ZIPs to
 * eliminate fixture pollution. Idempotent.
 *
 * Two cleanup modes:
 *   --dry-run            : only report how many rows would be affected
 *   (default)            : delete rows for periods 2026-02 and 2026-03 entirely
 *                          (they contain ONLY fixture data), and recompute
 *                          route_changes afterwards.
 *
 * The Jul 2025 — Jan 2026 overlap region is NOT deleted because these are
 * real BTS routes that just happen to coincide with fixture routes; a
 * re-ingestion of the real BTS monthly ZIPs will overwrite any stale fixture
 * values there.
 */

// Periods whose snapshots were generated ONLY by the sample fixture
// (scripts/generateSampleT100.ts). For these months no real BTS data has
// been ingested yet — deleting them eliminates forward-dated rows that
// contradict BTS's real 3-6 month publication lag.
const FIXTURE_ONLY_PERIODS = ['2026-02', '2026-03'];

// Comparison quarters that must be recomputed after cleanup. Any monthly
// period that maps to one of these quarters (via `monthToQuarter`) is
// considered tainted because its aggregates may have summed fixture rows.
const TAINTED_QUARTER_PREFIXES = new Set<string>();
for (const p of FIXTURE_ONLY_PERIODS) {
  TAINTED_QUARTER_PREFIXES.add(monthToQuarterPrefix(p));
}

function monthToQuarterPrefix(period: string): string {
  const [year, monthStr] = period.split('-');
  const month = parseInt(monthStr, 10);
  const quarter = Math.ceil(month / 3);
  return `${year}-Q${quarter}`;
}

async function cleanup(): Promise<void> {
  const dryRun = process.argv.includes('--dry-run');
  const pool = getPool();
  const client = await pool.connect();

  try {
    await client.query('BEGIN');

    const taintedQuarters = Array.from(TAINTED_QUARTER_PREFIXES);
    const ilikePatterns = taintedQuarters.map((q) => `${q}%`);

    const snapCount = await client.query<{ count: string }>(
      `SELECT COUNT(*)::text AS count FROM route_snapshots WHERE period = ANY($1)`,
      [FIXTURE_ONLY_PERIODS]
    );
    const changeCount = await client.query<{ count: string }>(
      `SELECT COUNT(*)::text AS count
       FROM route_changes
       WHERE comparison_period ILIKE ANY($1)`,
      [ilikePatterns]
    );

    logger.info('Fixture pollution scan', {
      snapshots_in_fixture_months: snapCount.rows[0].count,
      changes_in_tainted_quarters: changeCount.rows[0].count,
      fixture_months: FIXTURE_ONLY_PERIODS,
      tainted_quarters: taintedQuarters,
      dryRun,
    });

    if (dryRun) {
      await client.query('ROLLBACK');
      logger.info('Dry run complete (no rows modified)');
      return;
    }

    const deletedSnaps = await client.query(
      `DELETE FROM route_snapshots WHERE period = ANY($1)`,
      [FIXTURE_ONLY_PERIODS]
    );
    logger.info(`Deleted ${deletedSnaps.rowCount} route_snapshots rows`);

    // Purge any route_changes whose comparison quarter overlapped the fixture.
    // Recompute will regenerate them from the now-clean snapshots (likely with
    // fewer rows and lower confidence for the affected quarter, which is correct).
    const deletedChanges = await client.query(
      `DELETE FROM route_changes WHERE comparison_period ILIKE ANY($1)`,
      [ilikePatterns]
    );
    logger.info(
      `Deleted ${deletedChanges.rowCount} route_changes rows in tainted quarters`,
      { tainted_quarters: taintedQuarters }
    );
    logger.warn('Run `npm run recompute` after this script to rebuild route_changes');

    await client.query('COMMIT');
    logger.info('Fixture cleanup complete');
  } catch (err) {
    await client.query('ROLLBACK');
    throw err;
  } finally {
    client.release();
    await closePool();
  }
}

cleanup().catch((err) => {
  logger.error('Fixture cleanup failed', { error: String(err) });
  process.exit(1);
});
